import 'package:syria_offers_app/models/place.dart';

class TouristDataService {
  static List<Place> getAllPlaces() {
    return [
      // ======================= HOTELS =======================
      const Place(
        id: 'hotel-001',
        nameAr: 'فندق رويال سميراميس',
        nameEn: 'Royal Semiramis Hotel',
        category: PlaceCategory.hotel,
        descriptionAr: 'أول فندق 5 نجوم في سوريا (1950). مسبح على السطح، مطعمان. موقع مركزي مثالي.',
        descriptionEn: "Syria's first 5-star hotel (1950). Rooftop pool, two restaurants. Ideal central location.",
        galleryUrls: ['https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800'],
        latitude: 33.513, longitude: 36.278, openingHours: '24 ساعة',
        openingHoursEn: '24 hours',
      ),
      const Place(
        id: 'hotel-002',
        nameAr: 'فندق بيت زفران الساحر',
        nameEn: 'Beit Zafran Charm Hotel',
        category: PlaceCategory.hotel,
        descriptionAr: 'بوتيك في قلب دمشق القديمة. تديره وكالة نوافير للسفر.',
        descriptionEn: 'Boutique hotel in the heart of old Damascus, operated by Nawafir Travel.',
        galleryUrls: ['https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800'],
        latitude: 33.510, longitude: 36.292,
      ),
      const Place(
        id: 'hotel-003',
        nameAr: 'فندق بيت الولي',
        nameEn: 'Beit Al Wali Hotel',
        category: PlaceCategory.hotel,
        descriptionAr: 'بيت دمشقي من القرن 18. فخامة تقليدية وأجواء ترحيبية.',
        descriptionEn: '18th‑century Damascene house. Traditional luxury and welcoming atmosphere.',
        galleryUrls: ['https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800'],
        latitude: 33.5096, longitude: 36.3058, openingHours: '24 ساعة',
        openingHoursEn: '24 hours',
      ),
      const Place(
        id: 'hotel-004',
        nameAr: 'فندق شام بالاس',
        nameEn: 'Cham Palace Hotel',
        category: PlaceCategory.hotel,
        descriptionAr: '5 نجوم. بولينغ، 5 مطاعم، سينما خاصة، مسبح.',
        descriptionEn: '5‑star. Bowling, 5 restaurants, private cinema, pool.',
        galleryUrls: ['https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800'],
        latitude: 33.5160, longitude: 36.2880,
      ),
      const Place(
        id: 'hotel-005',
        nameAr: 'فندق ماندالون التراثي',
        nameEn: 'Mandaloune Heritage Hotel',
        category: PlaceCategory.hotel,
        descriptionAr: 'بوتيك رومانسي في حلب. مطعمان، بار مقبب.',
        descriptionEn: 'Romantic boutique hotel in Aleppo. Two restaurants, vaulted bar.',
        galleryUrls: ['https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800'],
        latitude: 36.200, longitude: 37.150,
      ),
      const Place(
        id: 'hotel-006',
        nameAr: 'منتجع أفاميا روتانا',
        nameEn: 'Afamia Rotana Resort',
        category: PlaceCategory.hotel,
        descriptionAr: '4 مطاعم، 2 مسبح خارجي، شاطئ خاص، سبا.',
        descriptionEn: '4 restaurants, 2 outdoor pools, private beach, spa.',
        galleryUrls: ['https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800'],
        latitude: 35.5215, longitude: 35.7814,
      ),
      const Place(
        id: 'hotel-007',
        nameAr: 'فندق لا ميرا',
        nameEn: 'La Mira Hotel',
        category: PlaceCategory.hotel,
        descriptionAr: '7 طوابق على البحر مباشرة. إطلالة 360°.',
        descriptionEn: '7‑story hotel right on the sea. 360° views.',
        galleryUrls: ['https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800'],
        latitude: 35.525, longitude: 35.770,
      ),
      const Place(
        id: 'hotel-008',
        nameAr: 'منتجع هوليداي بيتش',
        nameEn: 'Holiday Beach Resort',
        category: PlaceCategory.hotel,
        descriptionAr: '5 نجوم. شاطئ خاص. مسبح.',
        descriptionEn: '5‑star. Private beach. Pool.',
        galleryUrls: ['https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800'],
        latitude: 34.900, longitude: 35.870,
      ),
      const Place(
        id: 'hotel-009',
        nameAr: 'منتجع مشتى الحلو',
        nameEn: 'Mashta al‑Helou Resort',
        category: PlaceCategory.hotel,
        descriptionAr: 'منتجع جبلي على ارتفاع 950م. هواء نقي، كهف الضوايات.',
        descriptionEn: 'Mountain resort at 950m. Fresh air, Dawayat Cave nearby.',
        galleryUrls: ['https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800'],
        latitude: 34.8667, longitude: 36.2500,
      ),

      // ======================= RESTAURANTS =======================
      const Place(
        id: 'rest-001',
        nameAr: 'مطعم نارنج',
        nameEn: 'Naranj Restaurant',
        category: PlaceCategory.restaurant,
        descriptionAr: 'أشهر مطاعم دمشق في المدينة القديمة. أطباق سورية أصيلة، أجواء فاخرة.',
        descriptionEn: "Damascus' most famous restaurant in the Old City. Authentic Syrian cuisine.",
        galleryUrls: ['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800'],
        latitude: 33.5108, longitude: 36.3032, openingHours: '12:00 ظهراً - 11:00 مساءً',
        openingHoursEn: '12:00 noon - 11:00 PM',
      ),
      const Place(
        id: 'rest-002',
        nameAr: 'مطعم توبل - الفطور الدمشقي',
        nameEn: 'Tawabel Restaurant',
        category: PlaceCategory.restaurant,
        descriptionAr: 'بوفيه فطور في الطابق السابع من سميراميس. أطباق سورية تقليدية.',
        descriptionEn: 'Breakfast buffet on the 7th floor of Semiramis. Traditional Syrian dishes.',
        galleryUrls: ['https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=800'],
        latitude: 33.513, longitude: 36.278, openingHours: '7:00 صباحاً - 12:00 ظهراً',
        openingHoursEn: '7:00 AM - 12:00 noon',
      ),
      const Place(
        id: 'rest-003',
        nameAr: 'مطعم ماركو بولو',
        nameEn: 'Marco Polo Restaurant',
        category: PlaceCategory.restaurant,
        descriptionAr: 'المطعم الآسيوي الوحيد في سوريا. عشاء فقط.',
        descriptionEn: "Syria's only Asian fusion restaurant. Dinner only.",
        galleryUrls: ['https://images.unsplash.com/photo-1553621042-f6e147245754?w=800'],
        latitude: 33.513, longitude: 36.278, openingHours: '7:00 مساءً - 11:00 مساءً',
        openingHoursEn: '7:00 PM - 11:00 PM',
      ),
      const Place(
        id: 'rest-004',
        nameAr: 'رود هاوس ستيك هاوس',
        nameEn: 'Road House Steak House',
        category: PlaceCategory.restaurant,
        descriptionAr: 'أفضل ستيك في دمشق. حصص كبيرة، أجواء ممتازة.',
        descriptionEn: "Damascus' best steak. Generous portions, great atmosphere.",
        galleryUrls: ['https://images.unsplash.com/photo-1558030006-450675393462?w=800'],
        latitude: 33.540, longitude: 36.250,
      ),
      const Place(
        id: 'rest-005',
        nameAr: 'برازيل غورمي بيتزا آند غريل',
        nameEn: 'Brazil Gourmet Pizzeria & Grill',
        category: PlaceCategory.restaurant,
        descriptionAr: 'بيتزا نوتيلا الشهيرة. أجواء عائلية راقية.',
        descriptionEn: 'Famous Nutella pizza. Upscale family atmosphere.',
        galleryUrls: ['https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800'],
        latitude: 33.520, longitude: 36.290,
      ),
      const Place(
        id: 'rest-006',
        nameAr: 'مقهى د. فطاط',
        nameEn: 'Dr. Fattat',
        category: PlaceCategory.restaurant,
        descriptionAr: 'فطور فول وحمص 24 ساعة. مؤسسة دمشقية أسطورية.',
        descriptionEn: '24h foul & hummus. Legendary Damascus institution.',
        galleryUrls: ['https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800'],
        latitude: 33.5133, longitude: 36.2945, openingHours: '24 ساعة',
        openingHoursEn: '24 hours',
      ),
      const Place(
        id: 'rest-007',
        nameAr: 'مطعم حارتنا',
        nameEn: 'Haretna Restaurant',
        category: PlaceCategory.restaurant,
        descriptionAr: 'أجواء باب توما. أطباق سورية للعائلات.',
        descriptionEn: 'Bab Touma vibe. Syrian family dining.',
        galleryUrls: ['https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800'],
        latitude: 33.5105, longitude: 36.3150,
      ),
      const Place(
        id: 'rest-008',
        nameAr: 'مطعم بيت جبري',
        nameEn: 'Beit Jabri Restaurant',
        category: PlaceCategory.restaurant,
        descriptionAr: 'منزل دمشقي من 1737. فناء مع نافورة. شيشة.',
        descriptionEn: '1737 Damascene house. Courtyard fountain. Hookah.',
        galleryUrls: ['https://images.unsplash.com/photo-1559329007-40df8a9345d8?w=800'],
        latitude: 33.5110, longitude: 36.3080,
      ),
      const Place(
        id: 'rest-009',
        nameAr: 'مثلجات بكداش',
        nameEn: 'Bakdash Ice Cream',
        category: PlaceCategory.restaurant,
        descriptionAr: 'منذ 1895 في سوق الحميدية. آيس كريم المستكة الشهير.',
        descriptionEn: 'Since 1895 in Al‑Hamidiya Souq. Famous mastic ice cream.',
        galleryUrls: ['https://images.unsplash.com/photo-1551024506-0bccd828d307?w=800'],
        latitude: 33.5108, longitude: 36.3008, openingHours: '9:00 صباحاً - 10:00 مساءً',
        openingHoursEn: '9:00 AM - 10:00 PM',
      ),
      const Place(
        id: 'rest-010',
        nameAr: 'مطعم غراند ستيشن',
        nameEn: 'Grand Station Restaurant',
        category: PlaceCategory.restaurant,
        descriptionAr: 'إطلالة على قلعة حلب. أكل عصري وأجواء راقية.',
        descriptionEn: 'View of Aleppo Citadel. Modern cuisine and upscale ambiance.',
        galleryUrls: ['https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800'],
        latitude: 36.210, longitude: 37.140,
      ),
      const Place(
        id: 'rest-011',
        nameAr: 'غراند بلازا قرطبة',
        nameEn: 'Grand Plaza Qurtubah',
        category: PlaceCategory.restaurant,
        descriptionAr: 'مشويات، كبسة، بيتزا. أجواء عائلية.',
        descriptionEn: 'Grills, kabsa, pizza. Family atmosphere.',
        galleryUrls: ['https://images.unsplash.com/photo-1544025162-d76694265947?w=800'],
        latitude: 36.205, longitude: 37.155,
      ),
      const Place(
        id: 'rest-012',
        nameAr: 'مطعم شنب',
        nameEn: 'Shanab Restaurant',
        category: PlaceCategory.restaurant,
        descriptionAr: 'أشهر مطاعم حمص. أطباق لبنانية أصيلة.',
        descriptionEn: 'Most famous restaurant in Homs. Authentic Levantine dishes.',
        galleryUrls: ['https://images.unsplash.com/photo-1544025162-d76694265947?w=800'],
        latitude: 34.7333, longitude: 36.7167,
      ),
      const Place(
        id: 'rest-013',
        nameAr: 'مطعم مظاهر',
        nameEn: 'Mazaher Restaurant',
        category: PlaceCategory.restaurant,
        descriptionAr: 'في حي الحميدية. عمارة حجر بازلتي وخشب مزخرف.',
        descriptionEn: 'In Al‑Hamidiya district. Basalt stone architecture, ornate wood.',
        galleryUrls: ['https://images.unsplash.com/photo-1559329007-40df8a9345d8?w=800'],
        latitude: 34.730, longitude: 36.720,
      ),
      const Place(
        id: 'rest-014',
        nameAr: 'حلويات أبو اللبن',
        nameEn: 'Abu Al‑Laban Sweets',
        category: PlaceCategory.restaurant,
        descriptionAr: 'بشمانيه، فستق، كنافة. أشهر حلويات في حمص.',
        descriptionEn: 'Beshmeneh, pistachio, kunafa. Most famous sweets in Homs.',
        galleryUrls: ['https://images.unsplash.com/photo-1551024506-0bccd828d307?w=800'],
        latitude: 34.732, longitude: 36.718,
      ),
      const Place(
        id: 'rest-015',
        nameAr: 'مطعم المختار كفرام',
        nameEn: 'Al‑Mukhtar Kafram',
        category: PlaceCategory.restaurant,
        descriptionAr: 'مطعم في غابة الصنوبر. مشاوي ومزة كبيرة.',
        descriptionEn: 'Forest restaurant among pines. Grills and generous mezze.',
        galleryUrls: ['https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800'],
        latitude: 34.750, longitude: 36.650,
      ),

      // ======================= PARKS & NATUR =======================
      const Place(
        id: 'park-001',
        nameAr: 'حديقة تشرين',
        nameEn: 'Tishreen Park',
        category: PlaceCategory.park,
        descriptionAr: 'أكبر حديقة في دمشق (71 فدان). مسارات مشي، ملاعب أطفال، نوافير.',
        descriptionEn: 'Largest park in Damascus (71 acres). Walking paths, playgrounds, fountains.',
        galleryUrls: ['https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800'],
        latitude: 33.520, longitude: 36.270, openingHours: '8:00 صباحاً - 8:00 مساءً',
        openingHoursEn: '8:00 AM - 8:00 PM',
      ),
      const Place(
        id: 'park-002',
        nameAr: 'محمية غابات الفرنلق',
        nameEn: 'Al‑Furonlq Forest Reserve',
        category: PlaceCategory.park,
        descriptionAr: 'محمية طبيعية ساحلية. تخييم، مسارات، تنوع بيولوجي.',
        descriptionEn: 'Coastal nature reserve. Camping, trails, rich biodiversity.',
        galleryUrls: ['https://images.unsplash.com/photo-1448375240586-882707db888b?w=800'],
        latitude: 35.600, longitude: 36.000,
      ),
      const Place(
        id: 'park-003',
        nameAr: 'بحيرة 16 تشرين',
        nameEn: 'Lake 16 Tishreen',
        category: PlaceCategory.park,
        descriptionAr: 'بحيرة خلابة بين الجبال. صنوبر، بلوط، جزر صغيرة.',
        descriptionEn: 'Stunning lake surrounded by mountains. Pine, oak, small islands.',
        galleryUrls: ['https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800'],
        latitude: 35.6554, longitude: 35.9476,
      ),
      const Place(
        id: 'park-004',
        nameAr: 'شاطئ وادي قنديل',
        nameEn: 'Wadi Qandil Beach',
        category: PlaceCategory.park,
        descriptionAr: 'رمال سوداء. سباحة، غوص، استرخاء.',
        descriptionEn: 'Black sand beach. Swimming, snorkeling, relaxation.',
        galleryUrls: ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800'],
        latitude: 35.650, longitude: 35.850,
      ),
      const Place(
        id: 'park-005',
        nameAr: 'رأس البسيط',
        nameEn: 'Ras al‑Basit Beach',
        category: PlaceCategory.park,
        descriptionAr: 'من أجمل شواطئ المتوسط. غوص، مناظر خلابة.',
        descriptionEn: "One of the Mediterranean's finest beaches. Snorkeling, stunning views.",
        galleryUrls: ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800'],
        latitude: 35.850, longitude: 35.917,
      ),

      // ======================= AKTIVITÄTEN =======================
      const Place(
        id: 'act-001',
        nameAr: 'سوق الحميدية',
        nameEn: 'Al‑Hamidiya Souq',
        category: PlaceCategory.activity,
        descriptionAr: 'أكبر سوق مسقوف في سوريا (1780). أقمشة، ذهب، حلويات.',
        descriptionEn: 'Largest covered souq in Syria (1780). Fabrics, gold, sweets.',
        galleryUrls: ['https://images.unsplash.com/photo-1559589689-577aabd1db4f?w=800'],
        latitude: 33.5108, longitude: 36.3008, openingHours: '9:00 صباحاً - 8:00 مساءً',
        openingHoursEn: '9:00 AM - 8:00 PM',
      ),
      const Place(
        id: 'act-002',
        nameAr: 'سوق البزورية',
        nameEn: 'Souk al‑Bzourieh',
        category: PlaceCategory.activity,
        descriptionAr: 'بهارات وعطارة وحلويات خلف الجامع الأموي.',
        descriptionEn: 'Spices, perfumery and sweets behind the Umayyad Mosque.',
        galleryUrls: ['https://images.unsplash.com/photo-1465146633011-14f8e0781093?w=800'],
        latitude: 33.511, longitude: 36.306, openingHours: '9:00 صباحاً - 8:00 مساءً',
        openingHoursEn: '9:00 AM - 8:00 PM',
      ),
      const Place(
        id: 'act-003',
        nameAr: 'حمام نور الدين',
        nameEn: 'Hammam Nur al‑Din',
        category: PlaceCategory.activity,
        descriptionAr: 'حمام أيوبي تاريخي (1169). قباب رخامية.',
        descriptionEn: 'Historic Ayyubid bath (1169). Marble domes.',
        galleryUrls: ['https://images.unsplash.com/photo-1540555700478-4be289fbeca6?w=800'],
        latitude: 33.5094, longitude: 36.3065, openingHours: '9:00 صباحاً - 5:00 مساءً',
        openingHoursEn: '9:00 AM - 5:00 PM',
      ),
      const Place(
        id: 'act-004',
        nameAr: 'حمام البكري',
        nameEn: 'Hammam Al‑Bakri',
        category: PlaceCategory.activity,
        descriptionAr: 'أقدم حمام في دمشق (1069). حي باب توما.',
        descriptionEn: 'Oldest bath in Damascus (1069). Bab Touma neighborhood.',
        galleryUrls: ['https://images.unsplash.com/photo-1560185007-5f0bb1866cab?w=800'],
        latitude: 33.5108, longitude: 36.3150, openingHours: '9:00 صباحاً - 5:00 مساءً',
        openingHoursEn: '9:00 AM - 5:00 PM',
      ),
      const Place(
        id: 'act-005',
        nameAr: 'ورشة صابون حلبي تقليدي',
        nameEn: 'Aleppo Soap Workshop',
        category: PlaceCategory.activity,
        descriptionAr: 'زيارة ورشة صابون الغار. تراث عمره قرون.',
        descriptionEn: 'Visit a laurel soap workshop. Centuries‑old craft.',
        galleryUrls: ['https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=800'],
        latitude: 36.200, longitude: 37.155,
      ),
      const Place(
        id: 'act-006',
        nameAr: 'جزيرة أرواد - رحلة بالقارب',
        nameEn: 'Arwad Island Boat Trip',
        category: PlaceCategory.activity,
        descriptionAr: 'الجزيرة المأهولة الوحيدة في سوريا. غطس، أسواق.',
        descriptionEn: "Syria's only inhabited island. Snorkeling, local markets.",
        galleryUrls: ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800'],
        latitude: 34.855, longitude: 35.858,
      ),
      const Place(
        id: 'act-007',
        nameAr: 'تسلق جبال حميولي - كسب',
        nameEn: 'Kassab Himouli Hike',
        category: PlaceCategory.activity,
        descriptionAr: 'مسار 2 كم، ارتفاع 950م. غابات صنوبر.',
        descriptionEn: '2 km trail, 950m elevation. Pine forests.',
        galleryUrls: ['https://images.unsplash.com/photo-1551632811-561732d1e306?w=800'],
        latitude: 35.920, longitude: 35.980,
      ),
      const Place(
        id: 'act-008',
        nameAr: 'بولينغ شام بالاس',
        nameEn: 'Cham Palace Bowling',
        category: PlaceCategory.activity,
        descriptionAr: 'صالة بولينغ حديثة في فندق شام بالاس.',
        descriptionEn: 'Modern bowling alley at Cham Palace Hotel.',
        galleryUrls: ['https://images.unsplash.com/photo-1558734838-4c8c4c1c8c52?w=800'],
        latitude: 33.5160, longitude: 36.2880,
      ),

      // ======================= KINOS =======================
      const Place(
        id: 'cin-001',
        nameAr: 'سينما سيتي دمشق',
        nameEn: 'Cinema City Damascus',
        category: PlaceCategory.cinema,
        descriptionAr: 'سينما حديثة بشاشتين. تجربة 3D.',
        descriptionEn: 'Modern twin‑screen cinema. 3D experience.',
        galleryUrls: ['https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800'],
        latitude: 33.510, longitude: 36.290,
      ),
      const Place(
        id: 'cin-002',
        nameAr: 'سينما دمشق',
        nameEn: 'Cinema Dimashq',
        category: PlaceCategory.cinema,
        descriptionAr: '4 قاعات، بار سوشي. أحدث الأفلام.',
        descriptionEn: '4 screens, sushi bar. Latest movies.',
        galleryUrls: ['https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=800'],
        latitude: 33.512, longitude: 36.288,
      ),

      // ======================= FESTIVALS / EVENTS =======================
      const Place(
        id: 'fest-001',
        nameAr: 'مهرجان إشراقات - دار الأوبرا',
        nameEn: 'Ishraqat Festival – Opera House',
        category: PlaceCategory.event,
        descriptionAr: 'معرض فنون، تراث، مناطق تفاعلية. فبراير 2026.',
        descriptionEn: 'Art exhibition, heritage, interactive zones. February 2026.',
        galleryUrls: ['https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=800'],
        latitude: 33.512, longitude: 36.280,
      ),
      const Place(
        id: 'fest-002',
        nameAr: 'مهرجان حمص التراثي',
        nameEn: 'Homs Heritage Festival',
        category: PlaceCategory.event,
        descriptionAr: 'احتفال ثقافي. موسيقى، عروض تراثية. أبريل 2026.',
        descriptionEn: 'Cultural celebration. Music, heritage shows. April 2026.',
        galleryUrls: ['https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800'],
        latitude: 34.7333, longitude: 36.7167,
      ),
      const Place(
        id: 'fest-003',
        nameAr: 'مهرجان أكيتو - رأس السنة الآشورية',
        nameEn: 'Akitu Festival – Assyrian New Year',
        category: PlaceCategory.event,
        descriptionAr: 'رأس السنة الآشورية 6776. رقصات تقليدية. 4 أبريل 2026.',
        descriptionEn: 'Assyrian New Year 6776. Traditional dances. April 4, 2026.',
        galleryUrls: ['https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800'],
        latitude: 36.200, longitude: 37.150,
      ),
      const Place(
        id: 'fest-004',
        nameAr: 'جولة رمضان الكبرى',
        nameEn: 'Grand Ramadan Tour - 8 Days',
        category: PlaceCategory.event,
        descriptionAr: '8 أيام عبر سوريا. عائلات محلية، حرفيون. تجربة عمر.',
        descriptionEn: '8 days across Syria. Local families, craftsmen. Lifetime experience.',
        galleryUrls: ['https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800'],
        latitude: 33.510, longitude: 36.300,
      ),
      const Place(
        id: 'fest-005',
        nameAr: 'كرنفال مرمريتا',
        nameEn: 'Marmarita Carnival',
        category: PlaceCategory.event,
        descriptionAr: 'أزياء، موسيقى، رقص. 14 أغسطس 2026.',
        descriptionEn: 'Costumes, music, dance. August 14, 2026.',
        galleryUrls: ['https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800'],
        latitude: 34.7833, longitude: 36.2833,
      ),
      const Place(
        id: 'fest-006',
        nameAr: 'معرض سوريا للسفر 2026',
        nameEn: 'Syria Travel Show 2026',
        category: PlaceCategory.event,
        descriptionAr: '14–16 أبريل. فندق داما روز، دمشق.',
        descriptionEn: 'April 14–16. Dama Rose Hotel, Damascus.',
        galleryUrls: ['https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800'],
        latitude: 33.513, longitude: 36.280,
      ),
      const Place(
        id: 'fest-007',
        nameAr: 'مهرجان وطن - طرطوس',
        nameEn: 'Watan Festival Tartous',
        category: PlaceCategory.event,
        descriptionAr: 'عروض، بازار حرفي، مطاعم. مايو 2026.',
        descriptionEn: 'Shows, craft bazaar, restaurants. May 2026.',
        galleryUrls: ['https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800'],
        latitude: 34.890, longitude: 35.885,
      ),
    ];
  }
}